In [1]:

simple_grammar = """
sentence => noun_phrase verb_phrase
noun_phrase => Article Adj* noun
Adj* => null | Adj Adj*
verb_phrase => verb noun_phrase
Article =>  一个 | 这个
noun =>   女人 |  篮球 | 桌子 | 小猫
verb => 看着   |  坐在 |  听着 | 看见
Adj =>  蓝色的 | 好看的 | 小小的
"""

In [85]:
import numpy as np
b = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print(b[::2,::2])

[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [87]:
print(b[::-1,::2])

[[31 33 35]
 [26 28 30]
 [21 23 25]
 [16 18 20]
 [11 13 15]]


In [76]:
c = np.arange(10)
c[::3]

array([0, 3, 6, 9])

In [79]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
print(a[::2,::2])

[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [80]:
print(a[::2,::2])

[[11 13 15]
 [21 23 25]
 [31 33 35]]


In [65]:
print (type(a))

<class 'numpy.ndarray'>


In [ ]:
a = np.arange(25)
a = a.reshape(-1)
a

In [42]:
b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))

In [18]:
print(a ** 2)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [ ]:
print(a < b)

 print(a > b) 

print(a.dot(b))

np.add?

In [99]:
np.where?

In [104]:
np.where([[True, False],[False,False]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])

array([[1, 8],
       [7, 6]])

In [105]:
x = np.ones(5)
y = np.arange(4).reshape(4,1)
print (x)
print (y)

[1. 1. 1. 1. 1.]
[[0]
 [1]
 [2]
 [3]]


In [109]:
x+y


array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])